var GAME_LEVELS = [
    ["                          k   ooo                                                    ",
   "                         xxxxxxxxxxxx                                                       ",
   "                         x                                                        ",
   "                         x                                                        ",
   "                         x                                                        ",
   "                         x       h                                                 ",
   "                         x     xxxxxxx                                            ",
   "                    ooo  x                                                        ",
   "                 xxxxxxxxx                                                                ",
   "   ooo k                                                                            ",
   "xxxxxxxxx                                                                                 ",
   "                                                                                 ",
   "                                                                                 ",
   "                                                                                 ",
   "                                                                                 ",
   "                     ooo                                                           ",
   "                    xxxxx                                                             ",
   "                                                                                  ",
   "                                                                                ",
   "     x!!!!x                                                                            ",
   "     x!!!!x   xx                                                                 ",
   "     x!!!!x                                                                     ",
   "     x!!!!x                                                                     ",
   "     x!!!!x     xx                                                                ",
   "     x!!!!x          ooo                                                          ",
   "     x!!!!x         xxxxx                                                            ",
   "     x!!!!!!!!!!!!!!!!!!x                                                        ",
   "  @  x!!!!!!!!!!!!!!!!!!x      k    k                                          oo  ",
   "xxxxxx!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  [" x                                                                               x",
   " x                                       k    ooo                                x",
   " x                                    xxxxxxxxxxxxx                              x",
   " x                                   xx                                          x",
   " x                                xxxx                                           x",
   " x                             xxxx                                              x",
   " x     ooo   k                                                                   x",
   " xxxxxxxxxxxxxxx                                                                 x",
   " x                                                                               x",
   " x                                                                   ooo         x",
   " x                       ooo                              xxx      xxxxxx        x",
   " x                     xxxxxx                         xx    x!!!!!!x             x",
   " x                                 k               xxxx     xxxxxxxx             x",
   " x                                xxxxx        xxxxx               xo            x",
   " x                                                                 xxx           x",
   " x                                                                               x",
   " x  @                 ooo    ooo             k                        k    ooo   x",
   " xxxxxxxxxxxxx  xxx  xxxxx  xxxxx      xxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxx",
   "             x  x x  x   x  x   x!!!!!!x               x!!!!!x                     ",
   "             x!!x x!!x   x!!x   x!!!!!!x               xxxxxxx                     ",
   "             xxxx xxxx   xxxx   x!!!!!!x                                           ",
   "                                xxxxxxxx                                           ",
   "                                                                                 ",
   "                                                                                 "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "     @                                                 h                                                      ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
